-- Supabase Database Schema for Amader Family Hub
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

--------------------------------------------------------------------------------
-- 0. RESET SCHEMA (OPTIONAL: Uncomment these if you want a fresh start)
-- দয়া করে নিচের লাইনগুলোর শুরু থেকে -- সরিয়ে দিন যদি আপনি সবকিছু মুছে নতুনভাবে শুরু করতে চান।
--------------------------------------------------------------------------------
-- DROP TABLE IF EXISTS vault CASCADE;
-- DROP TABLE IF EXISTS notifications CASCADE;
-- DROP TABLE IF EXISTS poll_options CASCADE;
-- DROP TABLE IF EXISTS polls CASCADE;
-- DROP TABLE IF EXISTS events CASCADE;
-- DROP TABLE IF EXISTS gallery CASCADE;
-- DROP TABLE IF EXISTS tasks CASCADE;
-- DROP TABLE IF EXISTS land_records CASCADE;
-- DROP TABLE IF EXISTS expenses CASCADE;
-- DROP TABLE IF EXISTS members CASCADE;

--------------------------------------------------------------------------------
-- 1. TABLE DEFINITIONS (যদি টেবিল না থাকে তবে তৈরি করবে)
--------------------------------------------------------------------------------

-- Members Table
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_en TEXT,
  role TEXT,
  relation TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  score INTEGER DEFAULT 0,
  birth_year TEXT,
  death_year TEXT,
  location TEXT,
  story TEXT,
  is_deceased BOOLEAN DEFAULT FALSE,
  generation TEXT DEFAULT '২য় প্রজন্ম',
  parent_id BIGINT REFERENCES members(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC NOT NULL,
  category TEXT NOT NULL,
  date TEXT,
  description TEXT,
  member_id BIGINT REFERENCES members(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Land Records Table
CREATE TABLE IF NOT EXISTS land_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT,
  area TEXT,
  dag_no TEXT,
  status TEXT DEFAULT 'নিষ্পত্তি',
  docs_count INTEGER DEFAULT 0,
  value TEXT,
  last_updated TEXT,
  owner_id BIGINT REFERENCES members(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks Table
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  priority TEXT DEFAULT 'মাঝারি',
  status TEXT DEFAULT 'চলমান',
  deadline TEXT,
  member_id BIGINT REFERENCES members(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Gallery Table
CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  category TEXT,
  image_url TEXT NOT NULL,
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Events Table
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT,
  time TEXT,
  location TEXT,
  attendees INTEGER DEFAULT 0,
  type TEXT DEFAULT 'সভা',
  reminder BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Polls Table
CREATE TABLE IF NOT EXISTS polls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  status TEXT DEFAULT 'চলমান',
  deadline TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Poll Options Table
CREATE TABLE IF NOT EXISTS poll_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT REFERENCES polls(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  votes INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Notifications (Notices) Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT,
  type TEXT DEFAULT 'সাধারণ',
  is_read BOOLEAN DEFAULT FALSE,
  author TEXT DEFAULT 'অ্যাডমিন',
  pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Vault Table
CREATE TABLE IF NOT EXISTS vault (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  file_type TEXT DEFAULT 'এনক্রিপ্টেড',
  access_level TEXT DEFAULT 'শুধুমাত্র অ্যাডমিন',
  expiry TEXT DEFAULT 'কখনো না',
  file_size TEXT,
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

--------------------------------------------------------------------------------
-- 1.5. TABLE SYNCHRONIZATION (বিদ্যমান টেবিলে যদি কলাম না থাকে তবে যোগ করবে)
--------------------------------------------------------------------------------

-- Sync Members Table
DO $$ BEGIN
  ALTER TABLE members ADD COLUMN IF NOT EXISTS name_en TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS role TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS relation TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS phone TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS email TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS address TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS birth_year TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS death_year TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS location TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS story TEXT;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS is_deceased BOOLEAN DEFAULT FALSE;
  ALTER TABLE members ADD COLUMN IF NOT EXISTS generation TEXT DEFAULT '২য় প্রজন্ম';
  ALTER TABLE members ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES members(id);
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Sync Expenses Table
DO $$ BEGIN
  ALTER TABLE expenses ADD COLUMN IF NOT EXISTS amount NUMERIC;
  ALTER TABLE expenses ADD COLUMN IF NOT EXISTS category TEXT;
  ALTER TABLE expenses ADD COLUMN IF NOT EXISTS date TEXT;
  ALTER TABLE expenses ADD COLUMN IF NOT EXISTS description TEXT;
  ALTER TABLE expenses ADD COLUMN IF NOT EXISTS member_id BIGINT REFERENCES members(id);
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Sync Land Records Table
DO $$ BEGIN
  ALTER TABLE land_records ADD COLUMN IF NOT EXISTS location TEXT;
  ALTER TABLE land_records ADD COLUMN IF NOT EXISTS area TEXT;
  ALTER TABLE land_records ADD COLUMN IF NOT EXISTS dag_no TEXT;
  ALTER TABLE land_records ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'নিষ্পত্তি';
  ALTER TABLE land_records ADD COLUMN IF NOT EXISTS docs_count INTEGER DEFAULT 0;
  ALTER TABLE land_records ADD COLUMN IF NOT EXISTS value TEXT;
  ALTER TABLE land_records ADD COLUMN IF NOT EXISTS last_updated TEXT;
  ALTER TABLE land_records ADD COLUMN IF NOT EXISTS owner_id BIGINT REFERENCES members(id);
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Sync Tasks Table
DO $$ BEGIN
  ALTER TABLE tasks ADD COLUMN IF NOT EXISTS description TEXT;
  ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'মাঝারি';
  ALTER TABLE tasks ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'চলমান';
  ALTER TABLE tasks ADD COLUMN IF NOT EXISTS deadline TEXT;
  ALTER TABLE tasks ADD COLUMN IF NOT EXISTS member_id BIGINT REFERENCES members(id);
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Sync Polls Table
DO $$ BEGIN
  ALTER TABLE polls ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'চলমান';
  ALTER TABLE polls ADD COLUMN IF NOT EXISTS deadline TEXT;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

--------------------------------------------------------------------------------
-- 2. ENABLE ROW LEVEL SECURITY (RLS)
--------------------------------------------------------------------------------
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE land_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE polls ENABLE ROW LEVEL SECURITY;
ALTER TABLE poll_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE vault ENABLE ROW LEVEL SECURITY;

--------------------------------------------------------------------------------
-- 3. POLICIES (DROP IF EXISTS FIRST)
--------------------------------------------------------------------------------

-- Members Policies
DROP POLICY IF EXISTS "Allow public select members" ON members;
DROP POLICY IF EXISTS "Allow public insert members" ON members;
DROP POLICY IF EXISTS "Allow public update members" ON members;
CREATE POLICY "Allow public select members" ON members FOR SELECT USING (true);
CREATE POLICY "Allow public insert members" ON members FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update members" ON members FOR UPDATE USING (true);

-- Expenses Policies
DROP POLICY IF EXISTS "Allow public select expenses" ON expenses;
DROP POLICY IF EXISTS "Allow public insert expenses" ON expenses;
CREATE POLICY "Allow public select expenses" ON expenses FOR SELECT USING (true);
CREATE POLICY "Allow public insert expenses" ON expenses FOR INSERT WITH CHECK (true);

-- Land Records Policies
DROP POLICY IF EXISTS "Allow public select land_records" ON land_records;
DROP POLICY IF EXISTS "Allow public insert land_records" ON land_records;
CREATE POLICY "Allow public select land_records" ON land_records FOR SELECT USING (true);
CREATE POLICY "Allow public insert land_records" ON land_records FOR INSERT WITH CHECK (true);

-- Tasks Policies
DROP POLICY IF EXISTS "Allow public select tasks" ON tasks;
DROP POLICY IF EXISTS "Allow public insert tasks" ON tasks;
CREATE POLICY "Allow public select tasks" ON tasks FOR SELECT USING (true);
CREATE POLICY "Allow public insert tasks" ON tasks FOR INSERT WITH CHECK (true);

-- Gallery Policies
DROP POLICY IF EXISTS "Allow public select gallery" ON gallery;
DROP POLICY IF EXISTS "Allow public insert gallery" ON gallery;
CREATE POLICY "Allow public select gallery" ON gallery FOR SELECT USING (true);
CREATE POLICY "Allow public insert gallery" ON gallery FOR INSERT WITH CHECK (true);

-- Events Policies
DROP POLICY IF EXISTS "Allow public select events" ON events;
DROP POLICY IF EXISTS "Allow public insert events" ON events;
CREATE POLICY "Allow public select events" ON events FOR SELECT USING (true);
CREATE POLICY "Allow public insert events" ON events FOR INSERT WITH CHECK (true);

-- Polls Policies
DROP POLICY IF EXISTS "Allow public select polls" ON polls;
DROP POLICY IF EXISTS "Allow public insert polls" ON polls;
CREATE POLICY "Allow public select polls" ON polls FOR SELECT USING (true);
CREATE POLICY "Allow public insert polls" ON polls FOR INSERT WITH CHECK (true);

-- Poll Options Policies
DROP POLICY IF EXISTS "Allow public select poll_options" ON poll_options;
DROP POLICY IF EXISTS "Allow public insert poll_options" ON poll_options;
DROP POLICY IF EXISTS "Allow public update poll_options" ON poll_options;
CREATE POLICY "Allow public select poll_options" ON poll_options FOR SELECT USING (true);
CREATE POLICY "Allow public insert poll_options" ON poll_options FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update poll_options" ON poll_options FOR UPDATE USING (true);

-- Notifications Policies
DROP POLICY IF EXISTS "Allow public select notifications" ON notifications;
DROP POLICY IF EXISTS "Allow public insert notifications" ON notifications;
CREATE POLICY "Allow public select notifications" ON notifications FOR SELECT USING (true);
CREATE POLICY "Allow public insert notifications" ON notifications FOR INSERT WITH CHECK (true);

-- Vault Policies
DROP POLICY IF EXISTS "Allow public select vault" ON vault;
DROP POLICY IF EXISTS "Allow public insert vault" ON vault;
CREATE POLICY "Allow public select vault" ON vault FOR SELECT USING (true);
CREATE POLICY "Allow public insert vault" ON vault FOR INSERT WITH CHECK (true);

--------------------------------------------------------------------------------
-- 4. ROBUST SAMPLE DATA (Using PL/pgSQL for safety)
--------------------------------------------------------------------------------

DO $$ 
DECLARE 
    founder_id BIGINT;
    child1_id BIGINT;
    poll_id BIGINT;
BEGIN
    -- 4.1 Insert Founder
    IF NOT EXISTS (SELECT 1 FROM members WHERE name = 'মরহুম আব্দুল গফুর') THEN
        INSERT INTO members (name, name_en, role, relation, generation, is_deceased, birth_year, death_year, story)
        VALUES ('মরহুম আব্দুল গফুর', 'Abdul Gafur', 'প্রতিষ্ঠাতা', 'পরিবার প্রধান', '১ম প্রজন্ম', TRUE, '১৯৩০', '২০১৫', 'পরিবারের প্রতিষ্ঠাতা। তিনি কৃষি ও শিক্ষায় গুরুত্বপূর্ণ অবদান রেখেছেন।')
        RETURNING id INTO founder_id;
    ELSE
        SELECT id INTO founder_id FROM members WHERE name = 'মরহুম আব্দুল গফুর' LIMIT 1;
    END IF;

    -- 4.2 Insert Children (using founder_id as parent)
    IF NOT EXISTS (SELECT 1 FROM members WHERE name = 'আব্দুল করিম') THEN
        INSERT INTO members (name, name_en, role, relation, generation, parent_id, birth_year)
        VALUES ('আব্দুল করিম', 'Abdul Karim', 'সিনিয়র সদস্য', 'জ্যেষ্ঠ পুত্র', '২য় প্রজন্ম', founder_id, '১৯৫৫')
        RETURNING id INTO child1_id;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM members WHERE name = 'ফারুক আহমেদ') THEN
        INSERT INTO members (name, name_en, role, relation, generation, parent_id, birth_year)
        VALUES ('ফারুক আহমেদ', 'Faruk Ahmed', 'সদস্য', 'কনিষ্ঠ পুত্র', '২য় প্রজন্ম', founder_id, '১৯৬০');
    END IF;

    -- 4.3 Insert Expenses (using founder_id)
    -- We use a text literal '2026-03-27' which works for both DATE and TEXT types in PG.
    INSERT INTO expenses (amount, category, date, description, member_id)
    VALUES (500, 'খাবার', '2026-03-27', 'বাজার খরচ', founder_id),
           (1200, 'বিল', '2026-03-27', 'বিদ্যুৎ বিল', founder_id);

    -- 4.4 Insert Land Records
    INSERT INTO land_records (name, location, area, dag_no, status, docs_count, value, last_updated)
    VALUES ('পূর্বপাড়া কৃষিজমি', 'মৌজা: পূর্বপাড়া', '২.৫ একর', '১২৩৪', 'নিষ্পত্তি', 5, '৳১,৫০,০০,০০০', 'মার্চ ২০২৬');

    -- 4.5 Insert Tasks
    INSERT INTO tasks (title, status, priority)
    VALUES ('জমির খাজনা প্রদান', 'চলমান', 'উচ্চ'),
           ('পারিবারিক গেট-টুগেদার প্ল্যান', 'চলমান', 'মাঝারি');

    -- 4.6 Insert Notifications
    INSERT INTO notifications (title, message, type)
    VALUES ('নতুন সদস্য', 'আব্দুল করিম পরিবারে যুক্ত হয়েছেন', 'সফলতা'),
           ('জরুরী মিটিং', 'আগামী শুক্রবার জমি সংক্রান্ত মিটিং', 'সতর্কতা');

    -- 4.7 Insert Polls & Options
    IF NOT EXISTS (SELECT 1 FROM polls WHERE question = 'পারিবারিক পিকনিক কোথায় হবে?') THEN
        INSERT INTO polls (question, status, deadline)
        VALUES ('পারিবারিক পিকনিক কোথায় হবে?', 'চলমান', '৩০ মার্চ ২০২৬')
        RETURNING id INTO poll_id;

        INSERT INTO poll_options (poll_id, text, votes)
        VALUES (poll_id, 'কক্সবাজার', 12), (poll_id, 'সিলেট', 8), (poll_id, 'বান্দরবান', 5);
    END IF;

    -- 4.8 Insert Events
    INSERT INTO events (title, date, time, location, attendees, type, reminder)
    VALUES ('পারিবারিক সভা', '০১ এপ্রিল ২০২৬', 'সন্ধ্যা ৭:০০', 'ঢাকা কার্যালয়', 18, 'সভা', TRUE),
           ('ঈদুল ফিতর', '৩০ মার্চ ২০২৬', 'সকাল ১০:০০', 'গোপালগঞ্জ', 32, 'উৎসব', TRUE);

EXCEPTION WHEN OTHERS THEN 
    RAISE NOTICE 'Sample data insertion partially skipped or encountered issues: %', SQLERRM;
END $$;
